### ISSUE TITLE
Retire the Wiki

### ISSUE THREAD

**Issue by aqw** [psychoinformatics-de/inm7-docs#16]
These docs are still in-progress. But once we feel we have "enough" in here, we should announce the new docs to INM-7, and retire the Wiki, replacing it with a redirect to these docs.

Before retiring the wiki, a few things need to happen:
- [x] all issues tagged with "launch" need to be resolved
- [x] go through the Wiki thoroughly to make sure all (useful) content has been migrated
  - [x] Google Docs (contact list; books list; FZJ books list, Journal club, ~~Theses~~, Group Seminar, ~~Ethics~~)
  - [x] ~~Available datasets~~
  - [x] Ganglia
  - [ ] Jureca
- [x] crawl the wiki and download a copy, just in case (`wget -r [...]`)
- [x] setup a 301 redirect from the wiki to `docs.inm7.de`

**Comment by aqw** [comment]
crawled the wiki with:

```
wget --recursive \
     --no-clobber \
     --page-requisites \
     --html-extension \
     --convert-links \
     --domains brainball \
     --no-parent \
     http://brainball/mediawiki/
```

**Comment by loj** [comment]
Theses Overview and Ethics have already been migrated to sciebo by Claudia.

**Comment by FeHoff** [comment]
Hi, it's Felix.
For Ganglia I would suggest the 'Metric': "load_report" as default:

**Comment by aqw** [comment]
@FeHoff Done. Thanks. :-)

**Comment by aqw** [comment]
Done. Redirects to the new docs. :-)
