### ISSUE TITLE
Non-Technical Guides

### ISSUE THREAD

**Issue by aqw** [psychoinformatics-de/inm7-docs#5]
There's a few links which I am unsure how much they're used/needed, and whether they're a good fit for the docs.

My thought is that they're probably a better fit for Sciebo, but I am unsure yet on how documents are organized on there.

- PhD guide
- How to create grant application
- how to publish articles

**Comment by loj** [comment]
I think Sciebo is a better fit for these. I took a look, and all three are already on Sciebo under the folder "HowTo's". I think this makes sense and is a good place for them.

So, in my opinion this could be closed. Thoughts?

**Comment by aqw** [comment]
Makes sense to me. Thanks for checking this out.
