### ISSUE TITLE
Probably a more convenient way for declaring range in Condor submission file

### ISSUE THREAD

**Issue by jadecci** [psychoinformatics-de/inm7-docs#58]
Referring to the section https://docs.inm7.de/htcondor/submission_methods/#logical-submit-file, it should be possible to declare a range of values as arguments without creating the additional file `ncal_arguments.sh`.

Bascially, to use a range of 1000 to 1999, the command is simpy:

```
queue 1 arguments from seq 1000 1999 |
``` 

The pipe at the end lets Condor run "seq 1000 1999" as a shell command (see https://htcondor.readthedocs.io/en/latest/users-manual/submitting-a-job.html#using-the-power-and-flexibility-of-the-queue-command).

Hope this helps to make submission easier :)

**Comment by aqw** [comment]
@jadecci Yes! That particular feature apparently has been around for... forever, but was first documented a few months ago.

This should definitely be added to our docs, as it greatly simplifies many use cases.

**Comment by aqw** [comment]
I finally got around to this. Thanks again for sharing this approach. It is much nicer when `Queue`ing jobs. :-D
