### ISSUE TITLE
Create list of services and their authentication

### ISSUE THREAD

**Issue by aqw** [psychoinformatics-de/inm7-docs#7]
Services here at FZJ are pretty balkanized. Most authentication is ad-hoc and is not integrated into campus AD/Shibboleth.

We should create a list of services, link to their docs, and explain what auth it uses (so one can more easily determine which services they have access to).

Here is a quick start to the list:

- [x] FZJ Email, campus AD, https://docs.inm7.de/communication/#fzj%20email
- [x] VPN, VPN password, https://docs.inm7.de/network/#vpn
- [x] Eduroam, campus AD
- [x] wireless (same as eduroam?)
- [x] jugit, campus AD/jugit password, https://docs.inm7.de/services/#gitlab
- [x] gitlab, campus AD/jugit password, https://docs.inm7.de/services/#gitlab
- [x] gitlab.version, JuDoor user/password, https://docs.inm7.de/services/#gitlab
- [x] sciebo, campus AD/Sciebo password, https://docs.inm7.de/services/#file%20sharing
- [x] Judoor, JuDoor user/password, https://dspserv.zam.kfa-juelich.de/judoor/login
- [x] ~~Judocs~~
- [x] Slack, slack password
- [x] employee portal, employee portal username/password, intranet.fz-juelich.de/go/emapor
- [x] INM-7 Linux systems, NIS password
- [x] ITS Self Service, campus AD, https://its-servicedesk.fz-juelich.de/SelfService/
- [x] HDF Cloud, JuDoor
- [x] Library

**Comment by loj** [comment]
Information on the employee portal:

employee portal user/password
login at intranet.fz-juelich.de/go/emapor

A letter received in the first few weeks of starting will provide your username and initial password. There is a 6 volume manual on how to use the employee portal under the 'help' section on the main page of the portal.

**Comment by aqw** [comment]
@loj Thanks. :-) Updated

**Comment by loj** [comment]
Information for JuDoor:

JuDoor user/password

**Comment by aqw** [comment]
Still a few services left to add, but a /huge/ step forward. Thanks @loj for taking the first bite at this. :-)

**Comment by loj** [comment]
I looked into JuDocs and it seems to just serve as a resource for doctoral researchers/supervisors and doesn't require any account login. I don't think it belongs in the technical documentation.

**Comment by aqw** [comment]
This is largely done now. Yisss. :-D
